config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "employees#index"

  resources:employees
  
  
  get "/home" => "home#index"
  get "/dashboard" => "dashboard#homePage"
  get "dashboard/profile"

  get "home/about"
  get "dashboard/homePage"
  get "/login" => "dashboard#login"
  get "dashboard/signUp"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
      return unless user.present?
      can :read, :all
      return unless user.admin?
      can :manage, :all
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, :last_name, presence:true
    validates :email, :password,:confirm_password,:country, presence:true




    def fullname
        "#{first_name} #{last_name}".strip
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
         ROLES=%w{admin}

         def admin?
          role=='admin'
         end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  load_and_authorize_resource
  def profile
     
  end

  def homePage
  end

  def login
  end

  def signUp
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
    def index
        @employees=Employee.all
    end
    def new
      @employee = Employee.new
    end

    def create
        @employee = Employee.new(employee_params)

      if @employee.save
      redirect_to employees_path, notice: 'Employee has been created successfully!'
      else
      render :new
      end
    end

      def edit
        @employee = Employee.find(params[:id])
        end
      
      def update
        @employee = Employee.find(params[:id])
        if @employee.update(employee_params)
          redirect_to employees_path, notice: 'Employee has been updated successfully'
        else
          render :edit
          end
        end
      def show
        @employee = Employee.find(params[:id])

        end
      
        def destroy
        @employee = Employee.find(params[:id])
        if @employee.destroy
          redirect_to employees_path, notice: 'Employee has been Delete successfully'
        end


          end
      private

      def employee_params
        params.require(:employee).permit(:first_name, :last_name,:email,:password,:confirm_password,:country)
    end 
 end
 
  

app/controllers/home_controller.rb
class HomeController <ApplicationController
   load_and_authorize_resource
 def index
    @title="hello nouman sarwar welcome to Twinspider"

   #  if you uncomment it then its how not found page error
   #  render html: helpers.tag.strong('404 - Not Found Error')
   # display on the root page 
   # render file: "#{Rails.root}/public/404.html", layout: false 

 end
 def about
    @heading="This is about component"
    end
   
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/homePage.html.erb
<%= render 'shared/headers' %>

<h1>Dashboard#homePage</h1>
<p>Find me in app/views/dashboard/homePage.html.erb</p>

<%# here i use partail for same code list and changing style through one file in the shared folder instead of all %>
<%= render 'shared/links' %> 

app/views/dashboard/login.html.erb
<h1 style="color:red">Dashboard#login</h1>
<p>Find me in app/views/dashboard/login.html.erb</p>


<%= render 'shared/links' %>

app/views/dashboard/profile.html.erb
<h1>Dashboard#profile</h1>
<p>Find me in app/views/dashboard/profile.html.erb</p>

<%= render 'shared/links' %>

app/views/dashboard/signUp.html.erb
<h1>Dashboard#signUp</h1>
<p>Find me in app/views/dashboard/signUp.html.erb</p>

<%= render 'shared/links' %>

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>

<div>
    <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
</div>
  <div>
    <%= form.label :email %><br>
<%= form.email_field :email %>
</div>
  <div>
    <%= form.label :password %><br>
<%= form.password_field :password %>
</div>
  <div>
    <%= form.label :confirm_password %><br>
 <%= form.text_field :confirm_password %>
    </div>
      <div>
    <%= form.label :country %><br>
  <%= form.text_field :country %>
   
 </div>
  


  <div>
    <%= form.submit %>
    <%= link_to 'back to employees', employees_path %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit employee details<h1>

<%= render 'form', employee:@employee %>

app/views/employees/index.html.erb
<%= render 'shared/headers' %>
<%= flash[:notice]  %>
<table>
<thead>
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Full Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Confirm Password</th>
    <th>Country</th>
    <th>Action</th>
   


</tr>
</thead>
<tbody>
     <% @employees.each do |employee| %>
   
<tr>
    <td><%= employee.first_name %></td>
    <td><%= employee.last_name %></td>
    <%# here we create a func in employee model named as fullname and call it here%>
    <td><%= employee.fullname %></td>
    <td><%= employee.email %></td>
    <td><%= employee.password %></td>
    <td><%= employee.confirm_password%></td>
    <td><%= employee.country%></td>
    <td><%= link_to "Edit", edit_employee_path(employee) %></td>
    <td><%= link_to "View", employee_path(employee) %></td>
    <td><%= link_to "Delete", employee_path(employee), method: :delete, data: { confirm: 'Are you sure to delete this employee?' }  %></td>
 

    <% end %>
</tr>
</tbody>

    </table>

<%= link_to 'create new employee' , new_employee_path  %>

app/views/employees/new.html.erb
<h1>create new employee<h1>

<%= render 'form', employee:@employee %>

app/views/employees/show.html.erb
<h2>Employee detail<h2>
<table>
<thead>
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Full Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Confirm Password</th>
    <th>Country</th>


</tr>
</thead>
<tbody>
    
<tr>
    <td><%= @employee.first_name %></td>
    <td><%= @employee.last_name %></td>
    <%# here we create a func in employee model named as fullname and call it here%>
    <td><%= @employee.fullname %></td>
    <td><%= @employee.email %></td>
    <td><%= @employee.password %></td>
    <td><%= @employee.confirm_password%></td>
    <td><%= @employee.country%></td>
   

    
</tr>
</tbody>

    </table>


<%= link_to 'Back' , employees_path , class:'btn btn-primary btn-lg' %>
<%= link_to 'Edit' , edit_employee_path(@employee) , class:'btn btn-primary btn-lg' %>

app/views/home/about.html.erb
<h2> <%= @heading %><h2>
    <p>contact us<p>
        <input type='text' id='message'>

<%= render 'shared/links' %>

app/views/home/index.html.erb
<%= render 'shared/headers' %>
<h1> <%= @title %><h1>
<html>hello<html>
    
<%= link_to 'login' , login_path %>


<%= render 'shared/links' %>


<button class='btn btn-primary' >click me<button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Practice Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>

     
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_headers.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to "College Student App", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<ul>
    <li style="color:green">profile<li>
    <li style="color:green">homepage<li>
    <li style="color:green">sign up<li>
    <li style="color:green">login<li>

    <ul>